name: openapi_service_flutter_example
description: Example use of openapi code builder.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  logging: ^1.0.0
  logging_appenders: ^1.0.0
  dio: ^5.3.2
  either_dart: ^1.0.0
  mime: ^1.0.4
  openapi_service_flutter:
    path: ../

dev_dependencies:
  json_serializable: ^6.9.0
  freezed: ^3.1.0
  build_runner: ^2.4.13
  lints: ^6.0.0
