name: openapi_service_flutter
description: Generate type-safe Dart client libraries from OpenAPI specifications for Flutter apps.
version: 2.1.0+7
homepage: https://github.com/ChauCM/openapi_service_flutter
publish_to: none

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  # Code generation dependencies
  logging: ">=1.0.1 <2.0.0"
  logging_appenders: ^1.1.0
  meta: ">=1.5.0 <2.0.0"
  path: ">=1.8.0 <2.0.0"
  pub_semver: ">=2.0.0 <3.0.0"
  dart_style: ">=2.0.1 <4.0.0"
  code_builder: ">=4.0.0 <5.0.0"
  build: ">=2.0.2 <3.0.0"
  source_gen: ">=1.0.2 <3.0.0"
  open_api_dart:
    path: open-api-dart
  yaml: ">=3.1.0 <4.0.0"
  recase: ^4.1.0
  quiver: ">=3.0.1 <4.0.0"
  built_collection: ">=5.1.0 <6.0.0"
  collection: ">=1.15.0 <2.0.0"

  # Runtime dependencies (needed by generated code)
  dio: ">=5.0.0 <6.0.0"
  either_dart: ">=1.0.0 <2.0.0"

dev_dependencies:
  build_test: ^3.2.1
  lints: ^6.0.0
  test: ^1.26.2
  # For generating runtime models
  build_runner: ^2.4.7
