name: openapi_code_builder
description: Generate Dtos, client and server scaffolds for openapi specs.
version: 0.1.4
homepage: https://github.com/hpoul/openapi_dart/tree/master/packages/openapi_code_builder

environment:
  sdk: '>=2.8.0 <3.0.0'

dependencies:
  logging: ^1.0.0
  meta: ^1.3.0
  openapi_base: ^0.2.0
  path: ^1.8.0
  dart_style: ^2.0.0
  code_builder: ">=3.3.0 <4.0.0"
  build: ^2.0.0
  source_gen: ^1.0.0
  open_api_forked: ^3.0.0
  yaml: ^3.1.0
  json_annotation: ^4.0.1
  recase: ^4.0.0-nullsafety.0
  quiver: ^3.0.0
  built_collection: ^5.0.0

dev_dependencies:
  pedantic: ^1.11.0

dependency_overrides:
#  openapi_base:
#    path: ../openapi_base
  open_api_forked:
    path: ../../deps/open-api-dart
