name: openapi_code_builder
description: Generate Dtos, client and server scaffolds for openapi specs.
version: 0.1.1
homepage: https://github.com/hpoul/openapi_dart/tree/master/packages/openapi_code_builder

environment:
  sdk: '>=2.8.0 <3.0.0'

dependencies:
  logging: ^0.11.4
  meta: ^1.1.8
  openapi_base: ^0.1.0
  path: ^1.7.0
  dart_style: ^1.3.6
  code_builder: ^3.3.0
  build: ^1.3.0
  source_gen: ^0.9.5
  open_api_forked: ^2.0.1
  yaml: ^2.2.1
  json_annotation: ^3.0.1
  recase: ^3.0.0
  quiver: ^2.1.3
  built_collection: ^4.3.2

dev_dependencies:
  pedantic: ^1.9.0

dependency_overrides:
  openapi_base:
    path: ../openapi_base
  open_api:
    path: ../../deps/open-api-dart
