name: openapi_code_builder
description: Generate Dtos, client and server scaffolds for openapi specs.
version: 0.1.4+1
homepage: https://github.com/hpoul/openapi_dart/tree/master/packages/openapi_code_builder

environment:
  sdk: '>=2.8.0 <3.0.0'

dependencies:
  logging: ^1.0.1
  meta: ^1.6.0
  openapi_base: ^0.2.0+1
  path: ^1.8.0
  dart_style: ^2.0.1
  code_builder: ^4.0.0
  build: ^2.0.2
  source_gen: ^1.0.2
  open_api_forked: ^3.0.0+3
  yaml: ^3.1.0
  json_annotation: ^4.0.1
  recase: ^4.0.0
  quiver: ^3.0.1
  built_collection: ^5.1.0

dev_dependencies:
  pedantic: ^1.11.1

dependency_overrides:
#  openapi_base:
#    path: ../openapi_base
#  open_api_forked:
#    path: ../../deps/open-api-dart
