name: openapi_base
description: Open API base implementation for client/server.
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.9.0-13.0.dev <3.0.0'

dependencies:
#  path: ^1.7.0
  meta: ^1.1.8
  open_api: ^2.0.1
  shelf: ^0.7.5
  shelf_cookie: ^1.1.1
  uri: ^0.11.3+1
  logging: ^0.11.4
  logging_appenders: ^0.4.2+2

dev_dependencies:
  pedantic: ^1.9.0
