name: openapi_base
description: Open API base implementation for client/server.
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.9.0-13.0.dev <3.0.0'

dependencies:
#  path: ^1.7.0
  open_api: ^2.0.1

dev_dependencies:
  pedantic: ^1.9.0
