name: openapi_base
description: Open API base implementation for client/server to be used with openapi_code_builder.
version: 0.1.4
homepage: https://github.com/hpoul/openapi_dart/tree/master/packages/openapi_base

environment:
  sdk: '>=2.8.0 <3.0.0'

dependencies:
#  path: ^1.7.0
  meta: ">=1.1.8 <2.0.0"
  open_api_forked: ">=2.0.1+1 <3.0.0"
  uri: ^0.11.3+1
  logging: ">=0.11.4 <1.0.0"
  logging_appenders: ">=0.4.2+3 <1.0.0"

  uuid: ">=2.2.0 <3.0.0"
  json_annotation: ">=3.0.1 <4.0.0"

  # server
  shelf: ">=0.7.7 <1.0.0"
  shelf_cookie: ">=1.1.1 <2.0.0"

  # for the client:
  http: ">=0.12.1 <1.0.0"

dev_dependencies:
  pedantic: ^1.9.0
