name: open_api_dart
description: Data structures for OpenAPI (Swagger) specification. Reads and writes JSON specifications.
version: "3.1.1"
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  conduit_codable: ^5.1.5
  meta: ">=1.3.0 <2.0.0"

dev_dependencies:
  test: ">=1.16.4 <2.0.0"
  lints: ^6.0.0
